# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatData.proto',
  package='chatData',
  serialized_pb='\n\x0e\x63hatData.proto\x12\x08\x63hatData\"\x91\x01\n\x03MSG\x12\x0e\n\x06\x63hatid\x18\x01 \x02(\t\x12\x0e\n\x06userid\x18\x03 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12#\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x15.chatData.MSG.MsgData\x1a)\n\x07MsgData\x12\x10\n\x08SendTime\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x82\x02\n\x03\x43MD\x12\"\n\x03\x63md\x18\x02 \x02(\x0e\x32\x15.chatData.CMD.Command\x12\x0e\n\x06\x63hatid\x18\x03 \x01(\t\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12#\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x15.chatData.CMD.CmdData\x1a\x42\n\x07\x43mdData\x12\r\n\x05login\x18\x01 \x01(\t\x12\x0c\n\x04pswd\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x04 \x01(\t\"N\n\x07\x43ommand\x12\t\n\x05LOGIN\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x12\t\n\x05\x45NTER\x10\x03\x12\x08\n\x04QUIT\x10\x04\x12\x0c\n\x08REGISTER\x10\x05')



_CMD_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='chatData.CMD.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=357,
  serialized_end=435,
)


_MSG_MSGDATA = _descriptor.Descriptor(
  name='MsgData',
  full_name='chatData.MSG.MsgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SendTime', full_name='chatData.MSG.MsgData.SendTime', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='chatData.MSG.MsgData.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=174,
)

_MSG = _descriptor.Descriptor(
  name='MSG',
  full_name='chatData.MSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chatid', full_name='chatData.MSG.chatid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='chatData.MSG.userid', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='chatData.MSG.name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='chatData.MSG.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='chatData.MSG.data', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MSG_MSGDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=174,
)


_CMD_CMDDATA = _descriptor.Descriptor(
  name='CmdData',
  full_name='chatData.CMD.CmdData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='chatData.CMD.CmdData.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='chatData.CMD.CmdData.pswd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='chatData.CMD.CmdData.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='chatData.CMD.CmdData.args', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=289,
  serialized_end=355,
)

_CMD = _descriptor.Descriptor(
  name='CMD',
  full_name='chatData.CMD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='chatData.CMD.cmd', index=0,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chatid', full_name='chatData.CMD.chatid', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='chatData.CMD.userid', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='chatData.CMD.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CMD_CMDDATA, ],
  enum_types=[
    _CMD_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=435,
)

_MSG_MSGDATA.containing_type = _MSG;
_MSG.fields_by_name['data'].message_type = _MSG_MSGDATA
_CMD_CMDDATA.containing_type = _CMD;
_CMD.fields_by_name['cmd'].enum_type = _CMD_COMMAND
_CMD.fields_by_name['data'].message_type = _CMD_CMDDATA
_CMD_COMMAND.containing_type = _CMD;
DESCRIPTOR.message_types_by_name['MSG'] = _MSG
DESCRIPTOR.message_types_by_name['CMD'] = _CMD

class MSG(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class MsgData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MSG_MSGDATA

    # @@protoc_insertion_point(class_scope:chatData.MSG.MsgData)
  DESCRIPTOR = _MSG

  # @@protoc_insertion_point(class_scope:chatData.MSG)

class CMD(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class CmdData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CMD_CMDDATA

    # @@protoc_insertion_point(class_scope:chatData.CMD.CmdData)
  DESCRIPTOR = _CMD

  # @@protoc_insertion_point(class_scope:chatData.CMD)


# @@protoc_insertion_point(module_scope)
